### ISSUE TITLE
Supports python 3.9

### ISSUE THREAD

**Issue by nsano-rururu** [NodeCloudSrv/elastalert#6]
**elastalert/ruletypes.py**

from blist import sortedlist
  ↓
from sortedcontainers import SortedKeyList as sortedlist

**requirements.txt**

blist>=1.3.6
  ↓
sortedcontainers>=2.2.2

**setup.py**

'blist>=1.3.6',
  ↓
'sortedcontainers>=2.2.2',

**Comment by NodeCloudSrv** [comment]
blist in the CI testing on Github returned this: 
 blist/_blist.c: In function ‘py_blist_sort’:
      blist/_blist.c:6592:27: error: lvalue required as left operand of assignment
       6592 |         Py_REFCNT(&saved) = 1;
Look at the CI logs.

**Comment by NodeCloudSrv** [comment]
Python 3.10

**Comment by nsano-rururu** [comment]
blist does not support python 3.9 and 3.10.
You don't have the power to look it up yourself. I'm disappointed there.
https://github.com/DanielStutzbach/blist/issues

**Comment by nsano-rururu** [comment]
blist is no longer maintained. It's the same as elastalert. Understand first.

**Comment by nsano-rururu** [comment]
Also, just changing blist to sorted containers won't work in python 3.10.

**Comment by NodeCloudSrv** [comment]
Python 3.8 - successfully built blist.

**Comment by nsano-rururu** [comment]
Know. that kind of. After that, please do your best alone.

**Comment by nsano-rururu** [comment]
good bye

**Comment by nsano-rururu** [comment]
I told you how to deal with it. It ’s not good if it ’s not straightforward.

**Comment by nsano-rururu** [comment]
エンジニアとしての能力が非常に低いことがわかった。
